version: "3.3"
 
 
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # command: sh -c "npm i && npm start"
    ports:
      - 5173:5173
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    environment:
      REACT_APP_PORT: "5173"