version: "3.3"
 
 
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # command: sh -c "npm i && npm start"
    ports:
      - 4000:4000
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
